import { AdditiveDataType } from "@/types/definitions";

// _original_source: {
//     name: "Is It Vegan ?",
//     url: "https://github.com/isitvegan/isitvegan-web",
//     license: "MIT",
//     note: "Datas has been modified from its original version.",
//   },

export const veganAdditivesData: AdditiveDataType[] = [
  {
    description: "",
    e_number: "E133",
    link: "https://en.wikipedia.org/wiki/E133",
    name: "Bleu brillant FCF",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E140",
    link: "https://en.wikipedia.org/wiki/Chlorophyll",
    name: "Chlorophylles et chlorophyllines",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E141",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Complexes de cuivre de chlorophylles et de chlorophyllines",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E142",
    link: "https://en.wikipedia.org/wiki/E142",
    name: "Vert S",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E143",
    link: "https://en.wikipedia.org/wiki/E143",
    name: "Vert rapide FCF",
    status: "vegan",
  },
  {
    description:
      "Caramel ordinaire, obtenu par chauffage contrôlé de sucres alimentaires (comme le glucose, le saccharose)",
    e_number: "E150a",
    link: "https://en.wikipedia.org/wiki/E150a",
    name: "Caramel nature",
    status: "vegan",
  },
  {
    description: "Produit par chauffage de sucres en présence de sulfites",
    e_number: "E150b",
    link: "https://en.wikipedia.org/wiki/E150b",
    name: "Caramel au sulfite caustique",
    status: "vegan",
  },
  {
    description:
      "Produit par chauffage de sucres avec des composés ammoniacaux",
    e_number: "E150c",
    link: "https://en.wikipedia.org/wiki/E150c",
    name: "Caramel à l'ammoniaque",
    status: "vegan",
  },
  {
    description:
      "Produit par chauffage de sucres avec des sulfites et des composés ammoniacaux",
    e_number: "E150d",
    link: "https://en.wikipedia.org/wiki/E150d",
    name: "Caramel au sulfite d'ammoniaque",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E151",
    link: "https://en.wikipedia.org/wiki/E151",
    name: "Noir PN, Noir Brillant BN",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E152",
    link: "https://en.wikipedia.org/wiki/E152",
    name: "Noir de carbone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E154",
    link: "https://en.wikipedia.org/wiki/E154",
    name: "FK marron",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E155",
    link: "https://en.wikipedia.org/wiki/E155",
    name: "Brun HT",
    status: "vegan",
  },
  {
    description:
      "Pigment orange naturel provenant de carottes, potirons ou synthétisé.",
    e_number: "E160a",
    link: "https://en.wikipedia.org/wiki/E160a",
    name: "Alpha-carotène, bêta-carotène, gamma-carotène",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E160b",
    link: "https://en.wikipedia.org/wiki/E160b",
    name: "Rocou, bixine, norbixine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E160c",
    link: "https://en.wikipedia.org/wiki/E160c",
    name: "Oléorésine de paprika",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E160d",
    link: "https://en.wikipedia.org/wiki/E160d",
    name: "Lycopène",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E160e",
    link: "https://en.wikipedia.org/wiki/E160e",
    name: "Bêta-apo-8'-caroténal",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E160f",
    link: "https://en.wikipedia.org/wiki/E160f",
    name: "Ester éthylique de l'acide bêta-apo-8'-carotène",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E161a",
    link: "https://en.wikipedia.org/wiki/E161a",
    name: "Flavoxanthine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E161b",
    link: "https://en.wikipedia.org/wiki/E161b",
    name: "Lutéine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E161c",
    link: "https://en.wikipedia.org/wiki/E161c",
    name: "Cryptoxanthine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E161d",
    link: "https://en.wikipedia.org/wiki/E161d",
    name: "Rubixanthine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E161e",
    link: "https://en.wikipedia.org/wiki/E161e",
    name: "Violaxanthine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E161f",
    link: "https://en.wikipedia.org/wiki/E161f",
    name: "Rhodoxanthine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E162",
    link: "https://en.wikipedia.org/wiki/E162",
    name: "Betterave rouge, Bétanine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E163",
    link: "https://en.wikipedia.org/wiki/E163",
    name: "Anthocyanes",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E171",
    link: "https://en.wikipedia.org/wiki/E171",
    name: "Dioxyde de titane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E172",
    link: "https://en.wikipedia.org/wiki/E172",
    name: "Oxydes de fer et hydroxydes de fer",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E173",
    link: "https://en.wikipedia.org/wiki/E173",
    name: "Aluminium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E174",
    link: "https://en.wikipedia.org/wiki/E174",
    name: "Argent",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E175",
    link: "https://en.wikipedia.org/wiki/E175_(E_number)",
    name: "Or",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E180",
    link: "https://en.wikipedia.org/wiki/E180",
    name: "Pigment Rubin, Lithol Rubin BK",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E181",
    link: "https://en.wikipedia.org/wiki/Tannic_acid",
    name: "Tanin",
    status: "vegan",
  },
  {
    description:
      "D'origine végétale (venant du Sorbier des oiseaux - arbre à baies rouge des régions tempérées) ou synthétique",
    e_number: "E200",
    link: "https://en.wikipedia.org/wiki/Sorbic_acid",
    name: "Acide sorbique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E201",
    link: "https://en.wikipedia.org/wiki/Sodium_sorbate",
    name: "Sorbate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E202",
    link: "https://en.wikipedia.org/wiki/E202",
    name: "Sorbate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E203",
    link: "https://en.wikipedia.org/wiki/E203",
    name: "Sorbate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E210",
    link: "https://en.wikipedia.org/wiki/E210",
    name: "Acide benzoïque",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E211",
    link: "https://en.wikipedia.org/wiki/E211",
    name: "Benzoate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E212",
    link: "https://en.wikipedia.org/wiki/E212",
    name: "Benzoate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E213",
    link: "https://en.wikipedia.org/wiki/E213",
    name: "Benzoate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E214",
    link: "https://en.wikipedia.org/wiki/E214",
    name: "Éthylparabène",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E215",
    link: "https://en.wikipedia.org/wiki/E215",
    name: "Parahydroxybenzoate d'éthyle sodique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E216",
    link: "https://en.wikipedia.org/wiki/E216",
    name: "Propylparaben",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E217",
    link: "https://en.wikipedia.org/wiki/Sodium_propyl_para-hydroxybenzoate",
    name: "Parahydroxybenzoate de propyle sodique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E218",
    link: "https://en.wikipedia.org/wiki/E218",
    name: "Méthylparabène",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E219",
    link: "https://en.wikipedia.org/wiki/E219",
    name: "Parahydroxybenzoate de méthyle sodique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E220",
    link: "https://en.wikipedia.org/wiki/Sulfur_dioxide",
    name: "Dioxyde de soufre",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E221",
    link: "https://en.wikipedia.org/wiki/E221",
    name: "Sulfite de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E222",
    link: "https://en.wikipedia.org/wiki/E222",
    name: "Bisulfite de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E223",
    link: "https://en.wikipedia.org/wiki/E223",
    name: "Métabisulfite de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E224",
    link: "https://en.wikipedia.org/wiki/E224",
    name: "Métabisulfite de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E225",
    link: "https://en.wikipedia.org/wiki/E225",
    name: "Sulfite de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E226",
    link: "https://en.wikipedia.org/wiki/E226",
    name: "Sulfite de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E227",
    link: "https://en.wikipedia.org/wiki/E227",
    name: "Hydrogénosulfite de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E228",
    link: "https://en.wikipedia.org/wiki/E228",
    name: "Hydrogénosulfite de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E230",
    link: "https://en.wikipedia.org/wiki/E230",
    name: "Biphényle, diphényle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E231",
    link: "https://en.wikipedia.org/wiki/2-Phenylphenol",
    name: "Phénol orthophénylique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E232",
    link: "https://en.wikipedia.org/wiki/E232",
    name: "Phénol orthophénylique sodique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E233",
    link: "https://en.wikipedia.org/wiki/Thiabendazole",
    name: "Thiabendazole",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E234",
    link: "https://en.wikipedia.org/wiki/Nisin",
    name: "Nisine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E235",
    link: "https://en.wikipedia.org/wiki/E235",
    name: "Natamycine, Pimaracine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E236",
    link: "https://en.wikipedia.org/wiki/E236",
    name: "Acide formique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E237",
    link: "https://en.wikipedia.org/wiki/E237",
    name: "Formiate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E238",
    link: "https://en.wikipedia.org/wiki/E238",
    name: "Formiate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E239",
    link: "https://en.wikipedia.org/wiki/E239",
    name: "Hexamine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E240",
    link: "https://en.wikipedia.org/wiki/E240",
    name: "Formaldéhyde",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E242",
    link: "https://en.wikipedia.org/wiki/E242",
    name: "Dicarbonate de diméthyle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E249",
    link: "https://en.wikipedia.org/wiki/E249",
    name: "Nitrite de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E250",
    link: "https://en.wikipedia.org/wiki/Sodium_nitrite",
    name: "Nitrite de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E251",
    link: "https://en.wikipedia.org/wiki/E251",
    name: "Nitrate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E260",
    link: "https://en.wikipedia.org/wiki/Acetic_acid",
    name: "Acide acétique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E261",
    link: "https://en.wikipedia.org/wiki/Potassium_acetate",
    name: "Acétate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E262",
    link: "https://en.wikipedia.org/wiki/Sodium_acetate",
    name: "Acétates de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E263",
    link: "https://en.wikipedia.org/wiki/Calcium_acetate",
    name: "Acétate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E264",
    link: "https://en.wikipedia.org/wiki/Ammonium_acetate",
    name: "Acétate d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E280",
    link: "https://en.wikipedia.org/wiki/E280",
    name: "Acide propionique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E281",
    link: "https://en.wikipedia.org/wiki/E281",
    name: "Propionate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E282",
    link: "https://en.wikipedia.org/wiki/E282",
    name: "Propionate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E283",
    link: "https://en.wikipedia.org/wiki/E283",
    name: "Propionate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E284",
    link: "https://en.wikipedia.org/wiki/E284",
    name: "Acide borique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E285",
    link: "https://en.wikipedia.org/wiki/E285",
    name: "Tétraborate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E290",
    link: "https://en.wikipedia.org/wiki/E290",
    name: "Dioxyde de carbone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E296",
    link: "https://en.wikipedia.org/wiki/E296",
    name: "Acide malique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E297",
    link: "https://en.wikipedia.org/wiki/E297",
    name: "Acide fumarique",
    status: "vegan",
  },
  {
    description:
      "Antioxydant produit par fermentation de glucose à l’aide de bactéries",
    e_number: "E300",
    link: "https://en.wikipedia.org/wiki/Ascorbic_acid",
    name: "Acide ascorbique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E301",
    link: "https://en.wikipedia.org/wiki/E301",
    name: "Ascorbate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E302",
    link: "https://en.wikipedia.org/wiki/E302",
    name: "Ascorbate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E303",
    link: "https://en.wikipedia.org/wiki/E303",
    name: "Ascorbate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E304",
    link: "https://en.wikipedia.org/wiki/E304",
    name: "Esters d'acides gras de l'acide ascorbique",
    status: "vegan",
  },
  {
    description:
      "Correspond à la vitamine E d'origine naturelle. Produit à partir de sirops d'amidon",
    e_number: "E306",
    link: "https://en.wikipedia.org/wiki/E306",
    name: "Tocophérols",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E307",
    link: "https://en.wikipedia.org/wiki/E307",
    name: "Alpha-tocophérol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E308",
    link: "https://en.wikipedia.org/wiki/E308",
    name: "Gamma-tocophérol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E309",
    link: "https://en.wikipedia.org/wiki/E309",
    name: "Delta-tocophérol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E310",
    link: "https://en.wikipedia.org/wiki/Propyl_gallate",
    name: "Gallate de propyle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E311",
    link: "https://en.wikipedia.org/wiki/Octyl_gallate",
    name: "Gallate d'octyle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E312",
    link: "https://en.wikipedia.org/wiki/Dodecyl_gallate",
    name: "Gallate de dodécyle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E315",
    link: "https://en.wikipedia.org/wiki/E315",
    name: "Acide érythorbique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E316",
    link: "https://en.wikipedia.org/wiki/E316",
    name: "Érythorbate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E317",
    link: "https://en.wikipedia.org/wiki/E317",
    name: "Acide érythorbine[citation nécessaire]",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E318",
    link: "https://en.wikipedia.org/wiki/E318",
    name: "Érythorbine sodique[citation nécessaire]",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E319",
    link: "https://en.wikipedia.org/wiki/E319",
    name: "tert-butylhydroquinone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E320",
    link: "https://en.wikipedia.org/wiki/E320",
    name: "Hydroxyanisole butylé",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E321",
    link: "https://en.wikipedia.org/wiki/E321",
    name: "Hydroxytoluène butylé",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E329",
    link: "https://en.wikipedia.org/wiki/E329",
    name: "Lactate de magnésium",
    status: "vegan",
  },
  {
    description:
      "Acidifiant produit par fermentation de sous-produit de l'industrie agroalimentaire riche en sucres.",
    e_number: "E330",
    link: "https://en.wikipedia.org/wiki/E330",
    name: "Acide citrique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E331",
    link: "https://en.wikipedia.org/wiki/Sodium_citrate",
    name: "Citrates de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E332",
    link: "https://en.wikipedia.org/wiki/E332",
    name: "Citrates de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E333",
    link: "https://en.wikipedia.org/wiki/E333",
    name: "Citrates de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E334",
    link: "https://en.wikipedia.org/wiki/E334",
    name: "Acide tartrique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E335",
    link: "https://en.wikipedia.org/wiki/E335",
    name: "Tartrates de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E336",
    link: "https://en.wikipedia.org/wiki/E336",
    name: "Tartrates de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E337",
    link: "https://en.wikipedia.org/wiki/E337",
    name: "Tartrate de sodium et de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E338",
    link: "https://en.wikipedia.org/wiki/E338",
    name: "Acide phosphorique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E339",
    link: "https://en.wikipedia.org/wiki/E339",
    name: "Phosphates de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E340",
    link: "https://en.wikipedia.org/wiki/E340",
    name: "Phosphates de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E341",
    link: "https://en.wikipedia.org/wiki/E341",
    name: "Phosphates de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E343",
    link: "https://en.wikipedia.org/wiki/E343",
    name: "Phosphates de magnésium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E350",
    link: "https://en.wikipedia.org/wiki/E350_(food_additive)",
    name: "Malates de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E351",
    link: "https://en.wikipedia.org/wiki/E351",
    name: "Malate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E352",
    link: "https://en.wikipedia.org/wiki/E352",
    name: "Malates de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E353",
    link: "https://en.wikipedia.org/wiki/Metatartaric_acid",
    name: "Acide métatartrique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E354",
    link: "https://en.wikipedia.org/wiki/E354",
    name: "Tartrate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E355",
    link: "https://en.wikipedia.org/wiki/Adipic_acid",
    name: "Acide adipique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E356",
    link: "https://en.wikipedia.org/wiki/E356",
    name: "Adipate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E357",
    link: "https://en.wikipedia.org/wiki/E357",
    name: "Adipate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E363",
    link: "https://en.wikipedia.org/wiki/E363",
    name: "Acide succinique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E365",
    link: "https://en.wikipedia.org/wiki/Sodium_fumarate",
    name: "Fumarate monosodique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E366",
    link: "https://en.wikipedia.org/wiki/E366",
    name: "Fumarate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E367",
    link: "https://en.wikipedia.org/wiki/E367",
    name: "Fumarate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E370",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "1,4-Heptonolactone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E375",
    link: "https://en.wikipedia.org/wiki/Niacin_(substance)",
    name: "Niacine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E380",
    link: "https://en.wikipedia.org/wiki/Triammonium_citrate",
    name: "Citrate de triammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E381",
    link: "https://en.wikipedia.org/wiki/E381",
    name: "Citrate ferrique d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E385",
    link: "https://en.wikipedia.org/wiki/E385",
    name: "Éthylène diamine tétraacétate de calcium disodique,",
    status: "vegan",
  },
  {
    description: "",
    e_number: "e392",
    link: "https://fr.wikipedia.org/wiki/Extrait_de_romarin",
    name: "Extrait de Romarin",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E400",
    link: "https://en.wikipedia.org/wiki/Alginic_acid",
    name: "Acide alginique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E401",
    link: "https://en.wikipedia.org/wiki/E401",
    name: "Alginate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E402",
    link: "https://en.wikipedia.org/wiki/E402",
    name: "Alginate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E403",
    link: "https://en.wikipedia.org/wiki/E403",
    name: "Alginate d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E404",
    link: "https://en.wikipedia.org/wiki/E404",
    name: "Alginate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E405",
    link: "https://en.wikipedia.org/wiki/E405",
    name: "Alginate de propane-1,2-diol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E406",
    link: "https://en.wikipedia.org/wiki/E406",
    name: "Gélose",
    status: "vegan",
  },
  {
    description: "Gélifiants extraits par ébullition d’algues rouges",
    e_number: "E407",
    link: "https://en.wikipedia.org/wiki/E407",
    name: "Carraghénane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E407a",
    link: "https://en.wikipedia.org/wiki/E407a",
    name: "Algues eucheuma transformées",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E410",
    link: "https://en.wikipedia.org/wiki/Locust_bean_gum",
    name: "Gomme de caroube",
    status: "vegan",
  },
  {
    description: "Épaississant obtenu par broyage des graines du haricot guar",
    e_number: "E412",
    link: "https://en.wikipedia.org/wiki/Guar_gum",
    name: "Gomme de guar",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E413",
    link: "https://en.wikipedia.org/wiki/E413",
    name: "Adragante",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E414",
    link: "https://en.wikipedia.org/wiki/E414",
    name: "Gomme d'acacia",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E415",
    link: "https://en.wikipedia.org/wiki/E415",
    name: "Gomme xanthane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E416",
    link: "https://en.wikipedia.org/wiki/E416",
    name: "Gomme Karaya",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E417",
    link: "https://en.wikipedia.org/wiki/E417",
    name: "Gomme Tara",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E418",
    link: "https://en.wikipedia.org/wiki/E418",
    name: "Gomme gellane",
    status: "vegan",
  },
  {
    description:
      "Édulcorant produit par hydrogénation du glucose (généralement issu de maïs ou blé)",
    e_number: "E420",
    link: "https://en.wikipedia.org/wiki/E420",
    name: "Sorbitol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E421",
    link: "https://en.wikipedia.org/wiki/E421",
    name: "Mannitol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E425",
    link: "https://en.wikipedia.org/wiki/E425",
    name: "Konjac",
    status: "vegan",
  },
  {
    description:
      "Gélifiants naturels extraits des pelures et pépins de pommes ou agrumes.",
    e_number: "E440",
    link: "https://en.wikipedia.org/wiki/E440",
    name: "Pectines",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E444",
    link: "https://en.wikipedia.org/wiki/Sucrose_acetate_isobutyrate",
    name: "Acétate isobutyrate de saccharose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E445",
    link: "https://en.wikipedia.org/wiki/E445",
    name: "Esters glycériques de résines de bois",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E450",
    link: "https://en.wikipedia.org/wiki/E450_(food_additive)",
    name: "Diphosphates",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E451",
    link: "https://en.wikipedia.org/wiki/E451",
    name: "Triphosphates",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E452",
    link: "https://en.wikipedia.org/wiki/E452",
    name: "Polyphosphates",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E459",
    link: "https://en.wikipedia.org/wiki/E459",
    name: "Bêta-cyclodextrine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E460",
    link: "https://en.wikipedia.org/wiki/E460",
    name: "Cellulose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E461",
    link: "https://en.wikipedia.org/wiki/E461",
    name: "Méthylcellulose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E462",
    link: "https://en.wikipedia.org/wiki/E462",
    name: "Éthylcellulose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E463",
    link: "https://en.wikipedia.org/wiki/E463",
    name: "Hydroxypropylcellulose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E464",
    link: "https://en.wikipedia.org/wiki/Hypromellose",
    name: "Hypromellose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E465",
    link: "https://en.wikipedia.org/wiki/E465",
    name: "Éthylméthylcellulose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E466",
    link: "https://en.wikipedia.org/wiki/E466",
    name: "Carboxyméthylcellulose, Carboxyméthylcellulose sodique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E468",
    link: "https://en.wikipedia.org/wiki/E468",
    name: "Carboxyméthylcellulose de sodium réticulée",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E469",
    link: "https://en.wikipedia.org/wiki/E469",
    name: "Carboxyméthylcellulose hydrolysée par voie enzymatique",
    status: "vegan",
  },
  {
    description:
      "Régulateur d'acidité également employé comme antiagglomérant, agent levant, stabilisant ou épaississant. Produit principalement à partir de carbonate de sodium naturel et synthétique",
    e_number: "E500",
    link: "https://en.wikipedia.org/wiki/Sodium",
    name: "Carbonates de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E501",
    link: "https://en.wikipedia.org/wiki/Potassium",
    name: "Carbonates de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E503",
    link: "https://en.wikipedia.org/wiki/E503",
    name: "Carbonates d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E504",
    link: "https://en.wikipedia.org/wiki/E504",
    name: "Carbonates de magnésium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E507",
    link: "https://en.wikipedia.org/wiki/E507",
    name: "Acide chlorhydrique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E508",
    link: "https://en.wikipedia.org/wiki/E508",
    name: "Chlorure de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E509",
    link: "https://en.wikipedia.org/wiki/E509",
    name: "Chlorure de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E510",
    link: "https://en.wikipedia.org/wiki/Ammonium_chloride",
    name: "Chlorure d'ammonium, solution d'ammoniaque",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E511",
    link: "https://en.wikipedia.org/wiki/E511",
    name: "Chlorure de magnésium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E512",
    link: "https://en.wikipedia.org/wiki/E512",
    name: "Chlorure stanneux",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E513",
    link: "https://en.wikipedia.org/wiki/E513",
    name: "Acide sulfurique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E517",
    link: "https://en.wikipedia.org/wiki/E517",
    name: "Sulfate d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E518",
    link: "https://en.wikipedia.org/wiki/E518",
    name: "Sulfate de magnésium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E519",
    link: "https://en.wikipedia.org/wiki/E519",
    name: "Cuivre",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E520",
    link: "https://en.wikipedia.org/wiki/E520",
    name: "Sulfate d'aluminium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E521",
    link: "https://en.wikipedia.org/wiki/E521",
    name: "Sulfate d'aluminium et de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E522",
    link: "https://en.wikipedia.org/wiki/E522",
    name: "Sulfate d'aluminium et de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E523",
    link: "https://en.wikipedia.org/wiki/E523",
    name: "Sulfate d'aluminium et d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E524",
    link: "https://en.wikipedia.org/wiki/E524",
    name: "Hydroxyde de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E525",
    link: "https://en.wikipedia.org/wiki/E525",
    name: "Hydroxyde de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E526",
    link: "https://en.wikipedia.org/wiki/E526",
    name: "Hydroxyde de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E527",
    link: "https://en.wikipedia.org/wiki/E527",
    name: "Hydroxyde d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E528",
    link: "https://en.wikipedia.org/wiki/E528",
    name: "Hydroxyde de magnésium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E529",
    link: "https://en.wikipedia.org/wiki/E529",
    name: "Oxyde de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E530",
    link: "https://en.wikipedia.org/wiki/E530",
    name: "Oxyde de magnésium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E535",
    link: "https://en.wikipedia.org/wiki/E535",
    name: "Ferrocyanure de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E536",
    link: "https://en.wikipedia.org/wiki/E536",
    name: "Ferrocyanure de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E538",
    link: "https://en.wikipedia.org/wiki/E538",
    name: "Ferrocyanure de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E540",
    link: "https://en.wikipedia.org/wiki/Dicalcium_diphosphate",
    name: "Diphosphate dicalcique[citation nécessaire]",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E541",
    link: "https://en.wikipedia.org/wiki/E541",
    name: "Phosphate d'aluminium et de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E543",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Polyphosphate de calcium et de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E544",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Polyphosphate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E545",
    link: "https://en.wikipedia.org/wiki/E545",
    name: "Polyphosphate d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E550",
    link: "https://en.wikipedia.org/wiki/E550",
    name: "Silicates de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E551",
    link: "https://en.wikipedia.org/wiki/E551",
    name: "Dioxyde de silicium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E552",
    link: "https://en.wikipedia.org/wiki/E552",
    name: "Silicate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E553b",
    link: "https://en.wikipedia.org/wiki/E553b",
    name: "Talc",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E554",
    link: "https://en.wikipedia.org/wiki/E554",
    name: "Aluminosilicate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E555",
    link: "https://en.wikipedia.org/wiki/E555",
    name: "Silicate d'aluminium et de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E556",
    link: "https://en.wikipedia.org/wiki/E556",
    name: "Aluminosilicate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E558",
    link: "https://en.wikipedia.org/wiki/E558",
    name: "Bentonite",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E559",
    link: "https://en.wikipedia.org/wiki/E559",
    name: "Silicate d'aluminium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E574",
    link: "https://en.wikipedia.org/wiki/E574",
    name: "Acide gluconique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E575",
    link: "https://en.wikipedia.org/wiki/E575",
    name: "Glucono-delta-lactone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E576",
    link: "https://en.wikipedia.org/wiki/Gluconic_acid",
    name: "Gluconate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E577",
    link: "https://en.wikipedia.org/wiki/E577",
    name: "Gluconate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E578",
    link: "https://en.wikipedia.org/wiki/E578",
    name: "Gluconate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E579",
    link: "https://en.wikipedia.org/wiki/E579",
    name: "Gluconate ferreux",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E620",
    link: "https://en.wikipedia.org/wiki/E620",
    name: "Acide glutamique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E622",
    link: "https://en.wikipedia.org/wiki/E622",
    name: "Glutamate monopotassique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E623",
    link: "https://en.wikipedia.org/wiki/E623",
    name: "Diglutamate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E624",
    link: "https://en.wikipedia.org/wiki/E624",
    name: "Glutamate monoammonique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E625",
    link: "https://en.wikipedia.org/wiki/E625",
    name: "Diglutamate de magnésium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E626",
    link: "https://en.wikipedia.org/wiki/E626",
    name: "Acide guanylique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E629",
    link: "https://en.wikipedia.org/wiki/E629",
    name: "Guanylate de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E630",
    link: "https://en.wikipedia.org/wiki/E630",
    name: "Acide inosinique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E632",
    link: "https://en.wikipedia.org/wiki/Dipotassium_inosinate",
    name: "Inosinate dipotassique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E634",
    link: "https://en.wikipedia.org/wiki/E634",
    name: "5'-ribonucléotides calciques",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E636",
    link: "https://en.wikipedia.org/wiki/Maltol",
    name: "Maltol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E637",
    link: "https://en.wikipedia.org/wiki/Ethyl_maltol",
    name: "Éthyl maltol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E900",
    link: "https://en.wikipedia.org/wiki/Polydimethylsiloxane",
    name: "Diméthylpolysiloxane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E902",
    link: "https://en.wikipedia.org/wiki/E902",
    name: "Cire de candelilla",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E903",
    link: "https://en.wikipedia.org/wiki/E903",
    name: "Cire de carnauba",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E905",
    link: "https://en.wikipedia.org/wiki/E905",
    name: "Paraffines",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E905a",
    link: "https://en.wikipedia.org/wiki/E905a",
    name: "Huile minérale",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E905b",
    link: "https://en.wikipedia.org/wiki/E905b",
    name: "Vaseline",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E905c",
    link: "https://en.wikipedia.org/wiki/E905c",
    name: "Cire de pétrole",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E906",
    link: "https://en.wikipedia.org/wiki/E906",
    name: "Gomme benzoïque",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E907",
    link: "https://en.wikipedia.org/wiki/E907",
    name: "Cire cristalline",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E908",
    link: "https://en.wikipedia.org/wiki/E908",
    name: "Cire de son de riz",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E912",
    link: "https://en.wikipedia.org/wiki/E912",
    name: "Esters d'acide montanique, Esters d'acide montanique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E914",
    link: "https://en.wikipedia.org/wiki/E914",
    name: "Cire de polyéthylène oxydée, polyéthylène oxydé",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E915",
    link: "https://en.wikipedia.org/wiki/E915",
    name: "Esters de colophane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E922",
    link: "https://en.wikipedia.org/wiki/E922",
    name: "Persulfate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E923",
    link: "https://en.wikipedia.org/wiki/E923",
    name: "Persulfate d'ammonium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E924",
    link: "https://en.wikipedia.org/wiki/E924",
    name: "Bromate de potassium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E925",
    link: "https://en.wikipedia.org/wiki/E925",
    name: "Chlore",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E926",
    link: "https://en.wikipedia.org/wiki/E926",
    name: "Dioxyde de chlore",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E927a",
    link: "https://en.wikipedia.org/wiki/E927a",
    name: "Azodicarbonamide",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E927b",
    link: "https://en.wikipedia.org/wiki/E927b",
    name: "Carbamide",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E928",
    link: "https://en.wikipedia.org/wiki/E928",
    name: "Peroxyde de benzoyle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E930",
    link: "https://en.wikipedia.org/wiki/E930",
    name: "Peroxyde de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E938",
    link: "https://en.wikipedia.org/wiki/E938",
    name: "Argon",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E939",
    link: "https://en.wikipedia.org/wiki/E939",
    name: "Hélium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E940",
    link: "https://en.wikipedia.org/wiki/E940",
    name: "Dichlorodifluorométhane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E941",
    link: "https://en.wikipedia.org/wiki/E941",
    name: "Azote",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E942",
    link: "https://en.wikipedia.org/wiki/E942",
    name: "Protoxyde d'azote",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E943a",
    link: "https://en.wikipedia.org/wiki/E943a",
    name: "Butane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E943b",
    link: "https://en.wikipedia.org/wiki/E943b",
    name: "Isobutane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E944",
    link: "https://en.wikipedia.org/wiki/E944",
    name: "Propane",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E948",
    link: "https://en.wikipedia.org/wiki/E948",
    name: "Oxygène",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E949",
    link: "https://en.wikipedia.org/wiki/E949",
    name: "Hydrogène",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E950",
    link: "https://en.wikipedia.org/wiki/Acesulfame_potassium",
    name: "Acésulfame de potassium",
    status: "vegan",
  },
  {
    description:
      "Édulcorant artificiel utilisé dans les boissons light, desserts sans sucre. Origine synthétique",
    e_number: "E951",
    link: "https://en.wikipedia.org/wiki/E951",
    name: "Aspartame",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E952",
    link: "https://en.wikipedia.org/wiki/E952",
    name: "Acide cyclamique et ses sels de sodium et de calcium, également appelés cyclamates",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E953",
    link: "https://en.wikipedia.org/wiki/E953",
    name: "Isomalt, Isomaltitol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E954",
    link: "https://en.wikipedia.org/wiki/E954",
    name: "Saccharine et ses sels de sodium, de potassium et de calcium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E955",
    link: "https://en.wikipedia.org/wiki/E955",
    name: "Sucralose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E957",
    link: "https://en.wikipedia.org/wiki/E957",
    name: "Thaumatine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E959",
    link: "https://en.wikipedia.org/wiki/E959",
    name: "Dihydrochalcone de néohespéridine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E965",
    link: "https://en.wikipedia.org/wiki/E965",
    name: "Maltitol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E967",
    link: "https://en.wikipedia.org/wiki/E967",
    name: "Xylitol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E999",
    link: "https://en.wikipedia.org/wiki/E999",
    name: "Extrait de Quillaia",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1103",
    link: "https://en.wikipedia.org/wiki/E1103",
    name: "Invertase",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1200",
    link: "https://en.wikipedia.org/wiki/E1200",
    name: "Polydextrose",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1201",
    link: "https://en.wikipedia.org/wiki/E1201",
    name: "Polyvinylpyrrolidone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1202",
    link: "https://en.wikipedia.org/wiki/E1202",
    name: "Polyvinylpolypyrrolidone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1400",
    link: "https://en.wikipedia.org/wiki/E1400",
    name: "Dextrine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1401",
    link: "https://en.wikipedia.org/wiki/E1401",
    name: "Amidon modifié",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1402",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Amidon alcalin modifié",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1403",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Amidon blanchi",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1404",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Amidon oxydé",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1410",
    link: "https://en.wikipedia.org/wiki/E1410",
    name: "Phosphate de monoamidon",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1412",
    link: "https://en.wikipedia.org/wiki/E1412",
    name: "Phosphate de diamidon estérifié avec du trimétasphosphate de sodium; estérifié avec de l'oxychlorure de phosphore",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1413",
    link: "https://en.wikipedia.org/wiki/E1413",
    name: "Phosphate de diamidon phosphaté",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1414",
    link: "https://en.wikipedia.org/wiki/E1414",
    name: "Phosphate de diamidon acétylé",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1420",
    link: "https://en.wikipedia.org/wiki/E1420",
    name: "Acétate d'amidon estérifié avec de l'anhydride acétique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1421",
    link: "https://en.wikipedia.org/wiki/Stabilizer_(food)",
    name: "Acétate d'amidon estérifié avec de l'acétate de vinyle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1422",
    link: "https://en.wikipedia.org/wiki/E1422",
    name: "Adipate de diamidon acétylé",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1430",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Glycérine de diamidon",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1440",
    link: "https://en.wikipedia.org/wiki/E1440",
    name: "Amidon hydroxypropylique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1441",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Glycérine hydroxypropylique de diamidon",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1442",
    link: "https://en.wikipedia.org/wiki/E1442",
    name: "Phosphate de diamidon hydroxypropylique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1450",
    link: "https://en.wikipedia.org/wiki/E1450",
    name: "Octényl succinate d'amidon sodique",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1451",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Amidon oxydé acétylé",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1505",
    link: "https://en.wikipedia.org/wiki/E1505",
    name: "Citrate de triéthyle",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1510",
    link: "https://en.wikipedia.org/wiki/E1510",
    name: "Éthanol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1518",
    link: "https://en.wikipedia.org/wiki/E1518",
    name: "Triacétate de glycéryle ou triacétine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E1520",
    link: "https://en.wikipedia.org/wiki/E1520",
    name: "Propylène glycol",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E153",
    link: "https://en.wikipedia.org/wiki/E153",
    name: "Charbon végétal",
    status: "vegan",
  },
  {
    description:
      "Colorant jaune extrait du curcuma. Utilisé dans les plats préparés, les sauces, les produits à base de riz. Il est entièrement d’origine végétale.",
    e_number: "E100",
    link: "https://en.wikipedia.org/wiki/Curcumin",
    name: "Curcumine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E101",
    link: "https://en.wikipedia.org/wiki/Riboflavin",
    name: "Riboflavine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E101a",
    link: "https://en.wikipedia.org/wiki/Flavin_mononucleotide",
    name: "Riboflavine-5'-phosphate",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E106",
    link: "https://en.wikipedia.org/wiki/Flavin_mononucleotide",
    name: "Riboflavine-5-phosphate de sodium",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E102",
    link: "https://en.wikipedia.org/wiki/Tartrazine",
    name: "Tartrazine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E103",
    link: "https://en.wikipedia.org/wiki/Alkannin",
    name: "Alkannine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E104",
    link: "https://en.wikipedia.org/wiki/Quinoline_Yellow_WS",
    name: "Jaune de quinoléine WS",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E105",
    link: "https://en.wikipedia.org/wiki/Fast_Yellow_AB",
    name: "Jaune rapide AB",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E107",
    link: "https://en.wikipedia.org/wiki/Yellow_2G",
    name: "Jaune 2G",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E110",
    link: "https://en.wikipedia.org/wiki/Sunset_Yellow_FCF",
    name: "Jaune soleil FCF",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E111",
    link: "https://en.wikipedia.org/wiki/Orange_GGN",
    name: "Orange GGN",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E121",
    link: "https://en.wikipedia.org/wiki/Citrus_Red_2",
    name: "Rouge Agrumes 2",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E122",
    link: "https://en.wikipedia.org/wiki/Azorubine",
    name: "Azorubine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E123",
    link: "https://en.wikipedia.org/wiki/Amaranth_(dye)",
    name: "Amarante",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E124",
    link: "https://en.wikipedia.org/wiki/Ponceau_4R",
    name: "Ponceau 4R",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E125",
    link: "https://en.wikipedia.org/wiki/Scarlet_GN",
    name: "GN écarlate",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E126",
    link: "https://en.wikipedia.org/wiki/Ponceau_6R",
    name: "Ponceau 6R",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E127",
    link: "https://en.wikipedia.org/wiki/Erythrosine",
    name: "Érythrosine",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E128",
    link: "https://en.wikipedia.org/wiki/Red_2G",
    name: "Rouge 2G",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E129",
    link: "https://en.wikipedia.org/wiki/Allura_Red_AC",
    name: "Rouge Allura AC",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E131",
    link: "https://en.wikipedia.org/wiki/Patent_Blue_V",
    name: "Bleu indanthrone",
    status: "vegan",
  },
  {
    description: "",
    e_number: "E132",
    link: "https://en.wikipedia.org/wiki/Indigo_carmine",
    name: "Carmin indigo",
    status: "vegan",
  },
];

export const nonVeganAdditesData: AdditiveDataType[] = [
  {
    description: "Extrait d'œuf de poule",
    e_number: "E1105",
    link: "https://en.wikipedia.org/wiki/E1105",
    name: "Lysozyme",
    status: "carniste",
  },
  {
    description:
      "Gélifiant obtenu par hydrolyse du collagène contenu dans la peau, les os ou les cartilages d’animaux (porc, bœuf)",
    e_number: "E441",
    link: "https://en.wikipedia.org/wiki/E441",
    name: "Gélatine",
    status: "carniste",
  },
  {
    description: "",
    e_number: "E542",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Phosphate osseux",
    status: "carniste",
  },
  {
    description:
      "Agent d’enrobage ou de glaçage, obtenu par la fonte et filtration des alvéoles d’abeilles",
    e_number: "E901",
    link: "https://en.wikipedia.org/wiki/E901",
    name: "Cire d'abeille, blanche et jaune",
    status: "carniste",
  },
  {
    description:
      "Sécrété par un insecte (le Laccifer lacca), récolté sur les arbres tropicaux.",
    e_number: "E904",
    link: "https://en.wikipedia.org/wiki/E904",
    name: "Gomme laque",
    status: "carniste",
  },
  {
    description: "",
    e_number: "E910",
    link: "https://en.wikipedia.org/wiki/E910",
    name: "Esters de cire",
    status: "carniste",
  },
  {
    description: "Additif produit à partir de laine de mouton",
    e_number: "E913",
    link: "https://en.wikipedia.org/wiki/E913",
    name: "Lanoline",
    status: "carniste",
  },
  {
    description: "",
    e_number: "E966",
    link: "https://en.wikipedia.org/wiki/E966",
    name: "Lactitol",
    status: "carniste",
  },
  {
    description:
      "Colorant rouge issu des cochenilles (insectes écrasés). Présent dans certains bonbons, sodas, yaourts, glaces, ...",
    e_number: "E120",
    link: "https://en.wikipedia.org/wiki/Carmine",
    name: "Carmin",
    status: "carniste",
  },
];

export const maybeVeganAdditivesData: AdditiveDataType[] = [
  {
    description: "",
    e_number: "E170",
    link: "https://en.wikipedia.org/wiki/Calcium_carbonate",
    name: "Carbonate de calcium, craie",
    status: "Ça dépend",
  },
  {
    description:
      "Exhausteur de goût produit par fermentation de mélasse, amidon ou betterave avec des bactéries",
    e_number: "E621",
    link: "https://en.wikipedia.org/wiki/Monosodium_glutamate",
    name: "Glutamate monosodique",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E628",
    link: "https://en.wikipedia.org/wiki/E628",
    name: "Guanylate dipotassique",
    status: "Ça dépend",
  },
  {
    description:
      "Exhausteurs de goût. Peut être extrait de viandes/poissons ou produit par fermentation de sucres.",
    e_number: "E633",
    link: "https://en.wikipedia.org/wiki/Calcium_inosinate",
    name: "Inosinate de calcium",
    status: "Ça dépend",
  },
  {
    description:
      "Dérivés de la cystéine (acides aminés), parfois utilisés dans le pain pour améliorer la texture. Peut être extrait de poils ou plumes animales, bien que souvent produits aujourd’hui par fermentation.Il semble qu'en France, la l-cystéine soit très majoritairement d'origine végétale",
    e_number: "E920",
    link: "https://en.wikipedia.org/wiki/E920",
    name: "L-cystéine",
    status: "Ça dépend",
  },
  {
    description:
      "Dérivés de la cystéine (acides aminés), parfois utilisés dans le pain pour améliorer la texture. Peut être extrait de poils ou plumes animales, bien que souvent produits aujourd’hui par fermentation.Il semble qu'en France, la l-cystine soit très majoritairement d'origine végétale",
    e_number: "E921",
    link: "https://en.wikipedia.org/wiki/E921",
    name: "L-cystine",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E161g",
    link: "https://en.wikipedia.org/wiki/E161g",
    name: "Canthaxanthine",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E161h",
    link: "https://en.wikipedia.org/wiki/E161h",
    name: "Zéaxanthine",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E161i",
    link: "https://en.wikipedia.org/wiki/E161i",
    name: "Citranaxanthine",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E161j",
    link: "https://en.wikipedia.org/wiki/E161j",
    name: "Astaxanthine",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E252",
    link: "https://en.wikipedia.org/wiki/E252",
    name: "Nitrate de potassium",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E270",
    link: "https://en.wikipedia.org/wiki/E270",
    name: "Acide lactique",
    status: "Ça dépend",
  },
  {
    description:
      "Émulsifiants extraits principalement du soja ou du tournesol par pression à froid, mais aussi parfois du jaune d’œuf. Utilisés dans chocolat, margarines, gâteaux, ... À priori s'il est extrait d'oeuf, ça devrait être précisé sur l'emballage.",
    e_number: "E322",
    link: "https://en.wikipedia.org/wiki/E322",
    name: "Lécithine",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E325",
    link: "https://en.wikipedia.org/wiki/E325",
    name: "Lactate de sodium",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E326",
    link: "https://en.wikipedia.org/wiki/E326",
    name: "Lactate de potassium",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E327",
    link: "https://en.wikipedia.org/wiki/E327",
    name: "Lactate de calcium",
    status: "Ça dépend",
  },
  {
    description:
      "Agent humidifiant obtenu par hydrolyse des huiles (végétales comme palme, coco, ou animales). Il est possible qu'il soit d'origine animale sans que ça soit précisé sur l'emballage",
    e_number: "E422",
    link: "https://en.wikipedia.org/wiki/E422",
    name: "Glycérol",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E430",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Polyoxyéthylène",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E431",
    link: "https://en.wikipedia.org/wiki/E431",
    name: "Polyoxyéthylène",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E432",
    link: "https://en.wikipedia.org/wiki/E432",
    name: "Polyoxyéthylène",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E433",
    link: "https://en.wikipedia.org/wiki/E433",
    name: "Polyoxyéthylène",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E434",
    link: "https://en.wikipedia.org/wiki/E434",
    name: "Polyoxyéthylène",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E435",
    link: "https://en.wikipedia.org/wiki/E435",
    name: "Polyoxyéthylène",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E436",
    link: "https://en.wikipedia.org/wiki/E436",
    name: "Polyoxyéthylène",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E442",
    link: "https://en.wikipedia.org/wiki/E442",
    name: "Phosphatides d'ammonium",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E470a",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Sels de sodium, de potassium et de calcium d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E470b",
    link: "https://en.wikipedia.org/wiki/E470b",
    name: "Sels de magnésium d'acides gras",
    status: "Ça dépend",
  },
  {
    description:
      "Il sert comme émulsifiant, agent d'enrobage, gélifiant, antioxydant et support pour colorant. Il est obtenu à partir de graisse alimentaire d'origine animale, végétale ou synthétique. Même si le e471 provient en général de graisse végétale, il n'est pas totalement exclu d'en trouver provenant de cochons ou de boeuf. La mention de l'origine n'est pas obligatoire.",
    e_number: "E471",
    link: "https://en.wikipedia.org/wiki/E471",
    name: "Mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E472a",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Esters d'acide acétique de mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E472b",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Esters d'acide lactique de mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E472c",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Esters d'acide citrique de mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E472d",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Esters d'acide tartrique de mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E472e",
    link: "https://en.wikipedia.org/wiki/E472e",
    name: "Esters d'acide tartrique mono- et diacétyl de mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E472f",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Esters mixtes d'acide acétique et tartrique de mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E473",
    link: "https://en.wikipedia.org/wiki/E473",
    name: "Esters de saccharose d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E474",
    link: "https://en.wikipedia.org/wiki/Sucroglyceride",
    name: "Sucroglycérides",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E475",
    link: "https://en.wikipedia.org/wiki/E475",
    name: "Esters polyglycéroliques d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E476",
    link: "https://en.wikipedia.org/wiki/E476",
    name: "Polyricinoléate de polyglycérol",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E477",
    link: "https://en.wikipedia.org/wiki/E477",
    name: "Esters de propane-1,2-diol d'acides gras, esters de propylène glycol d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E478",
    link: "https://en.wikipedia.org/wiki/E_number",
    name: "Esters d'acides gras lactylés de glycérol et de propane-1",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E479b",
    link: "https://en.wikipedia.org/wiki/E479b",
    name: "Interaction de l'huile de soja oxydée thermiquement avec les mono- et diglycérides d'acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E481",
    link: "https://en.wikipedia.org/wiki/E481",
    name: "Stéaroyl-2-lactylate de sodium",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E482",
    link: "https://en.wikipedia.org/wiki/E482",
    name: "Stéaroyl-2-lactylate de calcium",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E483",
    link: "https://en.wikipedia.org/wiki/E483",
    name: "Tartrate de stéaryle",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E491",
    link: "https://en.wikipedia.org/wiki/E491",
    name: "Monostéarate de sorbitane",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E492",
    link: "https://en.wikipedia.org/wiki/E492",
    name: "Tristéarate de sorbitane",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E493",
    link: "https://en.wikipedia.org/wiki/E493",
    name: "Monolaurate de sorbitane",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E494",
    link: "https://en.wikipedia.org/wiki/E494",
    name: "Monooléate de sorbitane",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E495",
    link: "https://en.wikipedia.org/wiki/E495",
    name: "Monopalmitate de sorbitane",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E570",
    link: "https://en.wikipedia.org/wiki/E570",
    name: "Acides gras",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E572",
    link: "https://en.wikipedia.org/wiki/Magnesium_stearate",
    name: "Stéarate de magnésium, stéarate de calcium",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E585",
    link: "https://en.wikipedia.org/wiki/E585",
    name: "Lactate ferreux",
    status: "Ça dépend",
  },
  {
    description:
      "exhausteur de goût, souvent combiné au glutamate. Il est extrait de viandes/poissons séchés ou produit par fermentation de sucres avec des micro-organismes",
    e_number: "E627",
    link: "https://en.wikipedia.org/wiki/E627",
    name: "Guanylate disodique, guanylate de sodium",
    status: "Ça dépend",
  },
  {
    description:
      "exhausteur de goût dérivé de sources animales (poissons, viandes) ou par fermentation bactérienne sur substrats végétaux (comme la betterave ou la canne à sucre)",
    e_number: "E631",
    link: "https://en.wikipedia.org/wiki/E631",
    name: "Inosinate disodique",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E635",
    link: "https://en.wikipedia.org/wiki/E635",
    name: "5'-ribonucléotides disodiques",
    status: "Ça dépend",
  },
  {
    description: "",
    e_number: "E640",
    link: "https://en.wikipedia.org/wiki/E640",
    name: "Glycine et son sel de sodium",
    status: "Ça dépend",
  },
];

export const additivesData: AdditiveDataType[] = [
  ...veganAdditivesData,
  ...nonVeganAdditesData,
  ...maybeVeganAdditivesData,
];
